### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by bebe7452** [pd2-stuff/DLC-Unlocker-PD2#12]
I downloaded both BLT and Beardlib, created mods folder and dragged the file into there and etc. But for some reason when i start the game all the DLC's that are after 2019 Nov 7 is locked for some reason.

**Comment by 8fn** [comment]
> I downloaded both BLT and Beardlib, created mods folder and dragged the file into there and etc. But for some reason when i start the game all the DLC's that are after 2019 Nov 7 is locked for some reason.

Just to be sure, did u extract and drag the [unlock_all_dlcs](https://github.com/8fn/DLC-Unlocker-PD2/tree/master/unlock_all_dlcs) folder?
Send an screenshot
