### ISSUE TITLE
unlock outfits, gloves, perk decks, character/things that not get tagged "CHEATER"

### ISSUE THREAD

**Issue by proksii** [pd2-stuff/DLC-Unlocker-PD2#15]
Hello, can you make unlocker that give you things that not get under "CHEATER" tag? Thanks

**Comment by 8fn** [comment]
Sorry, I just saw it, I'll work on it

**Comment by 8fn** [comment]
https://github.com/pd2-stuff/DLC-Unlocker-PD2/tree/safe-unlock

Download it, it unlocks outfits, gloves, perck decks and characters. It would tag cheater tag, there is an outfit which still locked (dragon pack) because it unlock heist and it would tag cheater tag
