### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by iamcat2112** [pd2-stuff/DLC-Unlocker-PD2#21]
it's not working i already drag file

**Comment by iamcat2112** [comment]
![image](https://github.com/8fn/DLC-Unlocker-PD2/assets/132240212/d14fdb2c-15fb-41dd-895f-15052b06caca)

**Comment by 8fn** [comment]
put the unlock_all_dlcs folder, not the master folder

**Comment by taulantxhakli** [comment]
> put the unlock_all_dlcs folder, not the master folder

Yup, this is the correct answer. Was confused since both of the skin and dlc unlocker say master so I assumed it was correct. Thank you.
