### ISSUE TITLE
Some DLCs are unlocked, but a lot of them remain closed.

### ISSUE THREAD

**Issue by Nikforce730** [pd2-stuff/DLC-Unlocker-PD2#27]
I know there was an update in PAYDAY 2 recently and this issue could have been caused by that, but anyway...

**Comment by ALKOTS** [comment]
Which dlcs are closed?

**Comment by Nikforce730** [comment]
> Which dlcs are closed?

It's easier to list those that are closed, so all are closed except for Big Bank DLC, Jhon Wick heaists, Golden Grin casino, Scarface heast, The rest are closed.

**Comment by 8fn** [comment]
> > Which dlcs are closed?
> 
> It's easier to list those that are closed, so all are closed except for Big Bank DLC, Jhon Wick heaists, Golden Grin casino, Scarface heast, The rest are closed.

did u drag only unlock_all_dlcs folder? dont drag the masters folder
