### ISSUE TITLE
doesn't work, at all.

### ISSUE THREAD

**Issue by EEEPAPRYKA** [pd2-stuff/DLC-Unlocker-PD2#29]

**Comment by 8fn** [comment]
drag the unlock_all_dlcs folder

**Comment by 8fn** [comment]
not the masters folder

**Comment by wealthypotato** [comment]
> Collaborator

do we drag that folder into the mods folder?

**Comment by 8fn** [comment]
> 

u drag only the unlock_all_dlcs folder, read the [readme](https://github.com/pd2-stuff/DLC-Unlocker-PD2#%EF%B8%8Fwarning%EF%B8%8F)
