### ISSUE TITLE
Some Heist still locked

### ISSUE THREAD

**Issue by DW256** [pd2-stuff/DLC-Unlocker-PD2#30]
I'm using unlock_only_heist

List of locked heist :
- Dragon Heist
- Counterfeit
- Undercover

Screenshots : 
![image](https://github.com/pd2-stuff/DLC-Unlocker-PD2/assets/107021723/e6e0cfe9-b173-46dc-9c13-cfa6e8df6ce9)
![image](https://github.com/pd2-stuff/DLC-Unlocker-PD2/assets/107021723/600d119b-c7af-4f14-85e9-9aa90d7dbd72)

**Comment by 8fn** [comment]
> I'm using unlock_only_heist
> 
> List of locked heist :
> 
> * Dragon Heist
> * Counterfeit
> * Undercover
> 
> Screenshots : ![image](https://user-images.githubusercontent.com/107021723/248259560-e6e0cfe9-b173-46dc-9c13-cfa6e8df6ce9.png) ![image](https://user-images.githubusercontent.com/107021723/248259861-600d119b-c7af-4f14-85e9-9aa90d7dbd72.png)

Already updated it, download again unlock_only_heists
