### ISSUE TITLE
Unlocking the new DLC

### ISSUE THREAD

**Issue by DANser-freelancer** [pd2-stuff/DLC-Unlocker-PD2#32]
**Is your feature request related to a problem? Please describe.**
Not really a problem just a question. Do you still tend to this project? Will you work on unlocking the new "Crude Awakening" DLC?

**Describe the solution you'd like**
.

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by 8fn** [comment]
> Crude Awakening

It will unlock automatically, "unlock_all_dlcs" folder unlocks everything which is marked as "dlc"

**Comment by 8fn** [comment]
> **Is your feature request related to a problem? Please describe.** Not really a problem just a question. Do you still tend to this project? Will you work on unlocking the new "Crude Awakening" DLC?
> 
> **Describe the solution you'd like** .
> 
> **Describe alternatives you've considered** .
> 
> **Additional context** .



It will unlock automatically, "unlock_all_dlcs" folder unlocks everything which is marked as "dlc"

**Comment by ElHeistero** [comment]
> > **Is your feature request related to a problem? Please describe.** Not really a problem just a question. Do you still tend to this project? Will you work on unlocking the new "Crude Awakening" DLC?
> > **Describe the solution you'd like** .
> > **Describe alternatives you've considered** .
> > **Additional context** .
> 
> It will unlock automatically, "unlock_all_dlcs" folder unlocks everything which is marked as "dlc"

that's what i hoped too, sadly it doesn't work :(

**Comment by ElHeistero** [comment]
it works with the modification brought by the last pull request, thank you
