### ISSUE TITLE
Question about the mod's work

### ISSUE THREAD

**Issue by YaNePridumalNik** [pd2-stuff/DLC-Unlocker-PD2#35]
After downloading and installing - the game gives an error reading the data and resets all progress. What is the reason for this?

**Comment by 8fn** [comment]
> After downloading and installing - the game gives an error reading the data and resets all progress. What is the reason for this?

The issue is not from the mod, its a recent common issue from payday2 last update, its happening almost for everyone, it happened to me too and i dont have dlc unlocker
