### ISSUE TITLE
Specific heist DLCs are locked out

### ISSUE THREAD

**Issue by Cosmilks** [pd2-stuff/DLC-Unlocker-PD2#36]
HI! I used the "unlock_only_heists" folder, and i've had no issues so far except from the fact that **all the Armored Transport heists and Hotline Miami contracts are locked**, after your new update, it is _still locked_. I was just looking to farm Hotline Miami but am not able to. From my experience of "unlock_only_heists", **thats all the problems**. Other than that, this mod is perfect. was just looking if this was gonna get fixed any time soon (also seriously thank you for this mod)

**Comment by 8fn** [comment]
I will work into that

**Comment by 8fn** [comment]
> HI! I used the "unlock_only_heists" folder, and i've had no issues so far except from the fact that **all the Armored Transport heists and Hotline Miami contracts are locked**, after your new update, it is _still locked_. I was just looking to farm Hotline Miami but am not able to. From my experience of "unlock_only_heists", **thats all the problems**. Other than that, this mod is perfect. was just looking if this was gonna get fixed any time soon (also seriously thank you for this mod)

I updated unlock_only_heists, check if its working

**Comment by 8fn** [comment]
> HI! I used the "unlock_only_heists" folder, and i've had no issues so far except from the fact that **all the Armored Transport heists and Hotline Miami contracts are locked**, after your new update, it is _still locked_. I was just looking to farm Hotline Miami but am not able to. From my experience of "unlock_only_heists", **thats all the problems**. Other than that, this mod is perfect. was just looking if this was gonna get fixed any time soon (also seriously thank you for this mod)

I forgot to add armored transport heists, but i already added hotline miami

**Comment by 8fn** [comment]
I added armored transport heists, now it might work

**Comment by Cosmilks** [comment]
Hi 8fn, about to test it out

**Comment by Cosmilks** [comment]
> I added armored transport heists, now it might work

Thank you! everything works! every heist, including Hotline Miami is unlcoked. Thank you!

**Comment by Cosmilks** [comment]
Everything works now. Thank you 8fn!
