### ISSUE TITLE
Bonjour, j'ai installé votre mod plus le dossiers pour le faire fonctionner mais ça ne fonctionne pas pouvait m'éclairé s'il vous plait ?

### ISSUE THREAD

**Issue by Partimoxe** [pd2-stuff/DLC-Unlocker-PD2#37]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Send a screenshot of your mods folder

**Desktop (please complete the following information):**

**Steam or Epic? (please mark Y (yes)):**
 - Steam: [Y]
 - Epic [-]

**Additional context**

**Comment by azalty** [comment]
Dépose juste le dossier `unlock_all_dlcs` dans ton dossier `mods`, et ignore les autres.

**Comment by 8fn** [comment]
https://github.com/pd2-stuff/DLC-Unlocker-PD2#installation

**Comment by Partimoxe** [comment]
C'est bon j'avais réussi quand-même après mais merci quand-même et parler anglais non la flemme il fait comme moi google trad mdr

**Comment by 8fn** [comment]
> C'est bon j'avais réussi quand-même après mais merci quand-même et parler anglais non la flemme il fait comme moi google trad mdr

please speak english.

**Comment by azalty** [comment]
> please speak english.

yea, seems like they forgot how it works on internet

**Comment by Partimoxe** [comment]
> > Parlez Anglais, s'il vous plaît.
> 
> oui, on dirait qu'ils ont oublié comment ça marche sur internet

Parce que faut parler anglais sur internet ?

**Comment by 8fn** [comment]
> > > Parlez Anglais, s'il vous plaît.
> > 
> > 
> > oui, on dirait qu'ils ont oublié comment ça marche sur internet
> 
> Parce que faut parler anglais sur internet ?

jesus bro u fucking kidding m

**Comment by Partimoxe** [comment]
Use google traduction bro

**Comment by 8fn** [comment]
> Use google traduction bro

bro, google translate is for you, not for us... you are on the internet

**Comment by Partimoxe** [comment]
Internet = anglais ? je ne savais pas je pensais qu'on pouvait parler TOUTE les langues

**Comment by 8fn** [comment]
![image](https://github.com/pd2-stuff/DLC-Unlocker-PD2/assets/47666341/4863e284-d33e-420e-942b-594ca47bddc7)

**Comment by azalty** [comment]
> Internet = anglais ? je ne savais pas je pensais qu'on pouvait parler TOUTE les langues

English is the international language used all over the world and internet, and not French.

**Comment by Partimoxe** [comment]
Que ça soit une langue universelle ou pas ça ne veut pas dire qu'on doit TOUS parler anglais sur "le internet" xd. Par contre oui nous-mêmes on ne sait pas pourquoi ils ont rendu la langue française si dur
