### ISSUE TITLE
DLC unlocker not working

### ISSUE THREAD

**Issue by AzazelHD** [pd2-stuff/DLC-Unlocker-PD2#41]
Hello. Is this updated? I copied it into the payday2 mods folder, but it doesnt seem to unlock anything.

**Comment by 8fn** [comment]
Read the readme

**Comment by AzazelHD** [comment]
I dont know what do i need to read. I read it before openning an issue. LOL

**Comment by Vando442** [comment]
opened the game and dlc's are locked again. worked like an hour ago but doesnt work now and ive reinstalled them and its still locked.

**Comment by Vando442** [comment]
> opened the game and dlc's are locked again. worked like an hour ago but doesnt work now and ive reinstalled them and its still locked.

so messed around with what i downloaded a couple hours ago and i believe the problem was is that i updated node.v18 to node.v20, switched it back to v18 and it seems to be working fine as ive been looking through my inventory for a couple minutes now.

**Comment by 8fn** [comment]
⚠️If you want to unlock all DLCs, only drag the unlock_all_dlcs folder into the mods folder
⚠️If you only want to unlock Characters, only drag the unlock_only_characters folder into the mods folder
⚠️If you only want to unlock Heists, only drag the unlock_only_heists folder into the mods folder

**Comment by AzazelHD** [comment]
yeah, and i have only dragged the unlock_all_dlcs
![imagen](https://github.com/pd2-stuff/DLC-Unlocker-PD2/assets/47080553/8ce32c8d-ddd4-4897-bad8-56cb747f77a5)

I opened this issue cuz it was working 5 days ago. But now payday2 updated through steam, and it doesnt work anymore

**Comment by 8fn** [comment]
> yeah, and i have only dragged the unlock_all_dlcs ![imagen](https://user-images.githubusercontent.com/47080553/271790512-8ce32c8d-ddd4-4897-bad8-56cb747f77a5.png)
> 
> I opened this issue cuz it was working 5 days ago. But now payday2 updated through steam, and it doesnt work anymore

For me, its working, try to remove the folder, download it again and drag again the folder, also try to remove payday2 ultimate trainer to see if thats the cause

**Comment by AzazelHD** [comment]
When you buy any weapon, on the skin selector, do you have the skins? Because for me it says I must get the skin from a card after a heist or buy on the market.

**Comment by AzazelHD** [comment]
Why did you close the issue if it is not solved?

**Comment by AzazelHD** [comment]
So? Any updates so far? Or any possible fix?

**Comment by 8fn** [comment]
> When you buy any weapon, on the skin selector, do you have the skins? Because for me it says I must get the skin from a card after a heist or buy on the market.
> 
> ![imagen](https://user-images.githubusercontent.com/47080553/271840686-c9d27c56-5edc-4498-bbcf-45c8fc682975.png)
> 
> I also tried removing ultimate trainer and nothing
> 
> (The one i have is cuz probably I got it from a card)

This repository is dlc unlocked, not skins unlocker

**Comment by AzazelHD** [comment]
Oh. My bad. I thought it unlocks everything since it was calledd unlock all dlcs, and skills are dlcs too

**Comment by 8fn** [comment]
> Oh. My bad. I thought it unlocks everything since it was calledd unlock all dlcs, and skills are dlcs too

If you want skins
https://github.com/pd2-stuff/LegendarySkins-PD2

**Comment by AzazelHD** [comment]
Btw, is that proyect abandoned?

**Comment by 8fn** [comment]
No
