### ISSUE TITLE
Incompatible with RNG Modifier

### ISSUE THREAD

**Issue by tankyap** [pd2-stuff/DLC-Unlocker-PD2#45]
**Describe the bug**
Self-explanatory, cannot be compatible with the mod, but not the whole mod but the dlc weapon is, the maps are fine, it basically locks the DLC weapon.

**To Reproduce**
1. Install [RNG Modifier](https://modworkshop.net/mod/19913?tab=description) with the DLC weapon unlocker
2. Load Payday 2 as usual
3. DLC weapons are locked out.

**Expected behavior**
The DLC weapons didn't locked and RNG Modifier can be used as nothing happened

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Steam or Epic? (please mark Y (yes)):**
 - Steam: [-]
 - Epic [Y]

**Additional context**
None

**Comment by 8fn** [comment]
I use rngmodifier with dlc unlocker, it works :shrug:

**Comment by tankyap** [comment]
@8fn But the dlc weapons are unlocked somehow, idk man after I remove RNG modifier my weapons are back afterwards.

**Comment by tankyap** [comment]
Wait I kinda found whats problem here, so basically sometimes when it install each other. I can edit the RNG modifier but DLC weapons cannot unlocked and sometimes DLC unlocker unlocked the weapons but couldn't edit the RNG. Also do the same thing with [Faster drills.](https://www.nexusmods.com/payday2/mods/173)

**Comment by tankyap** [comment]
@tskxz Yeah looks like I realized that I can only install one of the unlock_(???) files after months. Welp I was dumb. Anyways thx for trying.
